
services:
  reservalab-web:
    build:
      context: ./
      dockerfile: Dockerfile.production
    image: reservalab-frontend:prod
    container_name: reservalab-frontend-stage
    hostname: frontend
    restart: unless-stopped
    ports:
      - "8000:80"
      - "5173:5173"
    # expose:
    #   - 8000
    environment:
      - VITE_API_URL=http://localhost:8080
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    networks:
      - reservalab-network

networks:
  reservalab-network:
    name: reservalab-network
    driver: bridge
