services:
  # Frontend - React com Vite
  reservalab-frontend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: reservalab-frontend:dev
    container_name: reservalab-frontend-dev
    ports:
      - "5173:5173"
    expose:
      - 5173
    environment:
      - VITE_API_URL=http://localhost:4000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - reservalab-network

networks:
  reservalab-network:
    driver: bridge
