version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend

  backend:
    build:
      context: ../seu-backend
    ports:
      - "3000:3000"
    volumes:
      - ../seu-backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://usuario:senha@db:5432/seubanco
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: seubanco
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
