# Dockerfile.dev
FROM node:20-alpine

# Define diretório de trabalho
WORKDIR /app

# Copia os arquivos de dependência e instala
COPY package*.json ./
RUN npm install

# Copia o restante do código
COPY . .

# Expõe a porta padrão do Vite
EXPOSE 5173

# Comando padrão para iniciar o Vite com hot reload
CMD ["npm", "run", "dev"]
